[build]
  command = "npm run build"
  publish = "dist/public"

# SPA fallback so client-side routes work on refresh and deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

## Security headers for all static assets
[[headers]]
  for = "/*"
  [headers.values]
    # Match server CSP (temporary 'unsafe-inline' to unblock inline scripts; plan to replace with nonces/hashes)
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; block-all-mixed-content; img-src 'self' data: https:; font-src 'self' https: data:; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; connect-src 'self' ws:"
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
